apiVersion: v1
kind: Namespace
metadata:
  name: ffmpeg
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ffmpeg-job
  namespace: ffmpeg
spec:
  template:
    spec:
      containers:
      - name: ffmpeg-container
        image: linuxserver/ffmpeg
        command: ["ffmpeg"]
        args:
        - "-re"
        - "-stream_loop"
        - "-1"
        - "-i"
        - "https://ent.box.com/shared/static/pnsp2zeix9tsvgi0u663i8kmmdypkx63.mp4"
        - "-c:v"  # Specify the video codec
        - "libx264"  # Use H.264 encoding
        - "-f"
        - "rtsp"
        - "rtsp://admin:abcd1234@10.255.255.135:554/stream1&channel=1"
      restartPolicy: Never
  backoffLimit: 4  
